-- Add nationwide ranking card types for the reviewed social-content workflow.
ALTER TYPE "SocialContentType" ADD VALUE IF NOT EXISTS 'NATIONAL_RAIN_WATCH';
ALTER TYPE "SocialContentType" ADD VALUE IF NOT EXISTS 'NATIONAL_AIR_QUALITY_WATCH';
ALTER TYPE "SocialContentType" ADD VALUE IF NOT EXISTS 'NATIONAL_HEAT_WATCH';
ALTER TYPE "SocialContentType" ADD VALUE IF NOT EXISTS 'NATIONAL_RIVER_WATCH';
ALTER TYPE "SocialContentType" ADD VALUE IF NOT EXISTS 'NATIONAL_ALERT_WATCH';
ALTER TYPE "SocialContentType" ADD VALUE IF NOT EXISTS 'NATIONAL_COMMUNITY_SIGNALS';
ALTER TYPE "SocialContentType" ADD VALUE IF NOT EXISTS 'NATIONAL_BIODIVERSITY';
